server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  datasource:
    driverClassName: org.postgresql.Driver
    password: password
    username: root
    url: jdbc:postgresql://localhost:5432/postgres
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  flyway:
    baseline-on-migrate: true
